// AUTO-GENERATED by test/single_joint_test/python/codegen_pd_gains.py.
// Do not edit by hand. Re-run the codegen script after changing g0.py.
//
// Source: G0_CFG.actuators stiffness/damping and G0_DEFAULT_JOINT_POS,
// converted to wire units:
//   kp           : N*m / deg
//   kd           : N*m / (deg/s)
//   default_pos  : deg
#ifndef G0_SJT_PD_GAINS_GENERATED_HPP
#define G0_SJT_PD_GAINS_GENERATED_HPP

#include <array>

namespace g0_sjt {

struct PdGain { float kp; float kd; };

static constexpr std::array<PdGain, 22> kPdGainsByMotorId = {{
    { 0.03490659f, 0.00139626f },  // id= 1  waist_yaw_joint  (standard_servos)
    { 0.03490659f, 0.00139626f },  // id= 2  waist_roll_joint  (standard_servos)
    { 0.02617994f, 0.00104720f },  // id= 3  l_shoulder_pitch_joint  (standard_servos)
    { 0.02617994f, 0.00104720f },  // id= 4  l_shoulder_roll_joint  (standard_servos)
    { 0.02617994f, 0.00104720f },  // id= 5  l_shoulder_yaw_joint  (standard_servos)
    { 0.03490659f, 0.00139626f },  // id= 6  l_elbow_pitch_joint  (right_angle_servos)
    { 0.02617994f, 0.00104720f },  // id= 7  r_shoulder_pitch_joint  (standard_servos)
    { 0.02617994f, 0.00104720f },  // id= 8  r_shoulder_roll_joint  (standard_servos)
    { 0.02617994f, 0.00104720f },  // id= 9  r_shoulder_yaw_joint  (standard_servos)
    { 0.03490659f, 0.00139626f },  // id=10  r_elbow_pitch_joint  (right_angle_servos)
    { 0.06981317f, 0.00314159f },  // id=11  l_hip_pitch_joint  (standard_servos)
    { 0.06981317f, 0.00279253f },  // id=12  l_hip_roll_joint  (standard_servos)
    { 0.05235988f, 0.00174533f },  // id=13  l_hip_yaw_joint  (standard_servos)
    { 0.06981317f, 0.00453786f },  // id=14  l_knee_pitch_joint  (right_angle_servos)
    { 0.06981317f, 0.00383972f },  // id=15  l_ankle_pitch_joint  (right_angle_servos)
    { 0.07853982f, 0.00261799f },  // id=16  l_ankle_roll_joint  (standard_servos)
    { 0.06981317f, 0.00314159f },  // id=17  r_hip_pitch_joint  (standard_servos)
    { 0.06981317f, 0.00279253f },  // id=18  r_hip_roll_joint  (standard_servos)
    { 0.05235988f, 0.00174533f },  // id=19  r_hip_yaw_joint  (standard_servos)
    { 0.06981317f, 0.00453786f },  // id=20  r_knee_pitch_joint  (right_angle_servos)
    { 0.06981317f, 0.00383972f },  // id=21  r_ankle_pitch_joint  (right_angle_servos)
    { 0.07853982f, 0.00261799f },  // id=22  r_ankle_roll_joint  (standard_servos)
}};

// G0_DEFAULT_JOINT_POS in degrees, indexed by (motor_id - 1).
// Sender uses this when --baseline default so non-target slots hold the
// standing pose instead of being commanded to zero.
static constexpr std::array<float, 22> kDefaultPosByMotorIdDeg = {{
    +0.00000000f,  // id= 1  waist_yaw_joint
    +0.00000000f,  // id= 2  waist_roll_joint
    -17.18873385f,  // id= 3  l_shoulder_pitch_joint
    -14.32394488f,  // id= 4  l_shoulder_roll_joint
    +0.00000000f,  // id= 5  l_shoulder_yaw_joint
    +55.57690613f,  // id= 6  l_elbow_pitch_joint
    +17.18873385f,  // id= 7  r_shoulder_pitch_joint
    +14.32394488f,  // id= 8  r_shoulder_roll_joint
    +0.00000000f,  // id= 9  r_shoulder_yaw_joint
    -55.57690613f,  // id=10  r_elbow_pitch_joint
    -11.45915590f,  // id=11  l_hip_pitch_joint
    +0.00000000f,  // id=12  l_hip_roll_joint
    +0.00000000f,  // id=13  l_hip_yaw_joint
    -19.48056503f,  // id=14  l_knee_pitch_joint
    +8.02140913f,  // id=15  l_ankle_pitch_joint
    +0.00000000f,  // id=16  l_ankle_roll_joint
    +11.45915590f,  // id=17  r_hip_pitch_joint
    +0.00000000f,  // id=18  r_hip_roll_joint
    +0.00000000f,  // id=19  r_hip_yaw_joint
    +19.48056503f,  // id=20  r_knee_pitch_joint
    -8.02140913f,  // id=21  r_ankle_pitch_joint
    +0.00000000f,  // id=22  r_ankle_roll_joint
}};

}  // namespace g0_sjt

#endif  // G0_SJT_PD_GAINS_GENERATED_HPP
